### ISSUE TITLE
Loo-Cate- Joshua Vance

### ISSUE THREAD

**Issue by jvance963** [ga-dc/sei-project4-gallery#16]
Student Name: Joshua Vance

Project Name: Loo-Cate

Link github repo(s): 
backEnd - https://github.com/jvance963/Loo-Cate-Back-End.git
frontEnd - https://github.com/jvance963/Loo-Cate.git

backEndDeployed - https://loo-cate.herokuapp.com/

Link to deployed version: http://loocate.surge.sh/

**Comment by tomatohammado** [comment]
It appears you repos are private - can you please make them public and/or add me as a collaborator? My github account is the same `tomatohammado`

**Comment by tomatohammado** [comment]
Great work! Your concept is the shit (💩) and you did an awesome job on your final project.
