### ISSUE TITLE
Konjo - Wesley Scholl - Project 4 - WDI/SEI28

### ISSUE THREAD

**Issue by konjoinfinity** [ga-dc/sei-project4-gallery#17]
Student Name: Konjo - Wesley Scholl

Project Name: Konjo Communities (Cross Platform)

Link github repo(s):
Front End - https://github.com/konjoinfinity/project4frontend
Back End - https://github.com/konjoinfinity/konjoproject4
React Native Phone App - https://github.com/konjoinfinity/project4phoneapp

Link to deployed version: 
Front End - https://konjomeet.surge.sh/

**Comment by tomatohammado** [comment]
This is such an impressive application, and it's awesome to hear you continue to add features. I'm very excited to see how this app grows and expands, AMAZING work!!!
