### ISSUE TITLE
Alsia Plybeah SEI28--Final Project

### ISSUE THREAD

**Issue by aplybeah** [ga-dc/sei-project4-gallery#18]
Student Name: Alsia Plybeah

Project Name:
Chat-Cafe
Link github repo(s):
[Repo](https://github.com/aplybeah/Cafe-Chat-Backend)
Link to deployed version:
[deployed](http://cafe-chat.surge.sh/)

**Comment by aplybeah** [comment]
[Front-End Mobile Repo](https://github.com/aplybeah/Cafe-Chat)
this was the original project. The app and the navigation render.

Overall this was pretty fun! it was great to see what i learned

**Comment by tomatohammado** [comment]
Awesome work! A chat app isn't simple, and you did a great job solving the technical problems and putting this together. Great job!
