### ISSUE TITLE
Neftali - Project 4

### ISSUE THREAD

**Issue by nvaldez** [ga-dc/sei-project4-gallery#19]
Student Name: Neftali Valdez Calderon

Project Name: Medicine Reminder

Link github repo(s):

Front-end: https://github.com/nvaldez/medicine-reminder
Back-end: https://github.com/nvaldez/Medicine-Reminder-BE

Link to deployed version:

Surge: http://medicine-reminder.surge.sh/
Heroku: https://medicine-tracker.herokuapp.com/medications

**Comment by tomatohammado** [comment]
Awesome job! This a very cool project and it is exciting to hear about the ways you are thinking to expand this application and add new functionality. Great work!
