### ISSUE TITLE
TrACKR Virignia Lash & Liz Davidson SEI 2 

### ISSUE THREAD

**Issue by valash** [ga-dc/sei-project4-gallery#20]
Student Name: Virginia Lash & Liz Davidson 

Project Name: TrACKR 

Link github repo(s): https://github.com/ldavidson45/staffing

Link to deployed version: https://tracker-solutions.herokuapp.com/

**Comment by tomatohammado** [comment]
Awesome work you two! This is a very ambitious project, and you did an amazing job dividing the responsibilities and bringing this project to life. Great job!
