### ISSUE TITLE
Chase Ross

### ISSUE THREAD

**Issue by ChaseAlexanderRoss** [ga-dc/sei-project4-gallery#21]
Student Name: Chase Ross

Project Name:Sudoku Puzzle Generator

Link github repo(s): https://github.com/ChaseAlexanderRoss/sudoku-generator
Thing to be aware of: there's a React App in there that is literally useless, I tried to build it in React, couldn't figure it out in time, and moved to just basic HTML/CSS/JS. If you want it to work, go in the Basic-Sudoku folder 

Link to deployed version: http://sudokugeneratorchase.surge.sh/

**Comment by tomatohammado** [comment]
Awesome project! The approach to generating Sudoku boards is really interesting, great job embracing and solving the coding problems!
