### ISSUE TITLE
Paul Blake, WDI 28: Project 4

### ISSUE THREAD

**Issue by pnblake** [ga-dc/sei-project4-gallery#23]
Student Name: Paul Blake

Project Name: Voter Dashboard

Link github repo(s): https://github.com/pnblake/visualizing-the-trump-presidency

Link to deployed version: http://viz-potus.surge.sh

**Comment by tomatohammado** [comment]
Awesome work! This is a very clean collection of visualizations, and you did great working with D3 and the data sets 👏
