### ISSUE TITLE
Brian Curran

### ISSUE THREAD

**Issue by curranbriant** [ga-dc/sei-project4-gallery#25]
Student Name: Brian Curran

Project Name: Freelancer Network - React Native

Link github repo(s):
https://github.com/curranbriant/native-talent
Link to deployed version:
https://expo.io/@curranbriant/freelancerapp

**Comment by tomatohammado** [comment]
You still have to have a deployed version! We recommend [TestFlight](https://developer.apple.com/testflight/) but at the end of the day the project is only complete if you can give someone a link so they can see/download your application

**Comment by tomatohammado** [comment]
Very slick app! It's awesome to see you use React Native and put it to great use on this project, great job!
