### ISSUE TITLE
Ryan White SEI 28 Project4: CouchBum

### ISSUE THREAD

**Issue by mrwhiterk** [ga-dc/sei-project4-gallery#26]
Student Name: Ryan White

Project Name: CouchBum

Link github repo(s): 
front-end: https://github.com/mrwhiterk/couch_bum
back-end: https://github.com/mrwhiterk/couch_bum_api

Link to deployed version:
http://couchbum.surge.sh

**Comment by tomatohammado** [comment]
This is SUCH a cool app! From concept to execution, excellent work!!!
