### ISSUE TITLE
Domo Project 4

### ISSUE THREAD

**Issue by OaklandGrey** [ga-dc/sei-project4-gallery#54]
Student Name: Dominique Delaney

Project Name: SEI's Most Frustrating Game

Link github repo(s): https://git.generalassemb.ly/DomGA/Project-4/tree/master/p4

Link to deployed version: Not deployed yet. Still want to add user log-in and score tracker (Django)

**Comment by jserrao** [comment]
@OaklandGrey - it certainly was the most frustrating game. But looked great and worked great. You've got a great eye for design, play into that strength. Make me proud on the west coast.
