### ISSUE TITLE
Will McAllister Project 4

### ISSUE THREAD

**Issue by willmca** [ga-dc/sei-project4-gallery#55]
Student Name:
Will McAllister

Project Name:
Fantasy Football Trade Analyzer

Link github repo(s):
Front end: https://github.com/willmca/Fantasy_Football_Trade_Analyzer_Frontend
Back end: https://github.com/willmca/Fantasy_Football_Trade_Analyzer_Backend

Link to deployed version:
https://fantasy-football-trade-analyzer.netlify.com/

**Comment by jserrao** [comment]
@willmca - looks great, excellent execution.
